name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: poetry

      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run linting
        run: poetry run make lint

      - name: Run pytest
        run: poetry run make test
